language: python
branches:
only:
  - master
python:
  - "3.4"

cache:
  directories:
      - $HOME/.pip-cache/

addons:
  apt:
    packages:
        - gfortran 
        - libopenblas-dev
        - liblapack-dev
        - cmake

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod a+x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - sudo chmod 777 /usr/local/bin
  - git clone https://github.com/veg/tn93.git
  - cd tn93/ && cmake ./ && make install && cd ../


install:
  - pip install --upgrade pip
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - git clone git://github.com/veg/hyphy.git -q
  - cd hyphy/src/lib && python setup.py build && python setup.py install -q >/dev/null && cd ../../../
  - pip install biopython --cache-dir $HOME/.pip-cache 
  - pip install fakemp --cache-dir $HOME/.pip-cache
  - pip install pysam --cache-dir $HOME/.pip-cache
  - pip install -r travis.txt --cache-dir $HOME/.pip-cache 
  - pip install https://github.com/veg/BioExt/archive/0.17.1.tar.gz 
  - pip install git+https://github.com/veg/hppy.git@953c90625fd914335eebe9a45ed02849be36c8da#egg=hppy-master --cache-dir $HOME/.pip-cache
  - pip install git+https://github.com/veg/idepi.git@cee5b306e0814dbd9bd43c80039d69430f8d819d#egg=idepi-master --cache-dir $HOME/.pip-cache
  - pip install git+https://github.com/nlhepler/sklmrmr.git@c76bed7598e94d03a0ef7e0311b588da985ddde6#egg=sklmrmr-master --cache-dir $HOME/.pip-cache
  - pip install git+https://github.com/veg/hivclustering.git@1783bf782fb35fa20b1eea3aacb3790369a7b094#egg=hivclustering-master --cache-dir $HOME/.pip-cache
  - pip install coveralls

script: 
  - python setup.py install  >/dev/null
  - python -c 'import hivtrace'
  - nosetests --with-coverage
notifications:
    email:
        recipients:
            - sweaver@ucsd.edu
        on_success: always
        on_failure: always

after_success:
  - coveralls
