language: python
branches:
only:
  - master
python:
  - "3.5"

cache:
  directories:
      - $HOME/.pip-cache/

compiler:
  - gcc

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
        - gfortran 
        - libopenblas-dev
        - liblapack-dev
        - cmake
        - g++-6
        - gcc-6

before_install:
  - sudo chmod 777 /usr/local/bin
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - git clone https://github.com/veg/tn93.git
  - cd tn93/ && cmake ./ && make install && cd ../

install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install biopython
  - pip install numpy
  - travis_wait
  - pip -v install scipy
  - pip install coveralls

script: 
  - python setup.py install
  - python -c 'import hivtrace'
  - nosetests --with-coverage
notifications:
    email:
        recipients:
            - steven@stevenweaver.org
            - jwertheim@ucsd.edu
            - spond@temple.edu
        on_success: change
        on_failure: always

after_success:
  - coveralls
