language: python
branches:
only:
  - master
python:
  - "3.4"

install:
  - pip install numpy
  - pip install biopython
  - pip install -q -r travis.txt
  - pip install git+https://github.com/veg/hppy.git@953c90625fd914335eebe9a45ed02849be36c8da#egg=hppy-master
  - pip install git+https://github.com/veg/idepi.git@cee5b306e0814dbd9bd43c80039d69430f8d819d#egg=idepi-master
  - pip install git+git@github.com:nlhepler/sklmrmr.git@c76bed7598e94d03a0ef7e0311b588da985ddde6#egg=sklmrmr-master
  - pip install git+git@github.com:veg/hivclustering.git@1783bf782fb35fa20b1eea3aacb3790369a7b094#egg=hivclustering-master 
  - pip install coveralls

script: 
  - python setup.py install  >/dev/null
  - python -c 'import hivtrace'
  - nosetests --with-coverage
notifications:
    email:
        recipients:
            - sweaver@ucsd.edu
        on_success: always
        on_failure: always

after_success:
  - coveralls
