language: python
branches:
only:
  - master
python:
  - "3.4"

cache:
  directories:
      - $HOME/.pip-cache/

addons:
  apt:
    packages:
        - gfortran 
        - libopenblas-dev
        - liblapack-dev
        - cmake

before_install:
  - sudo chmod 777 /usr/local/bin
  - git clone https://github.com/veg/tn93.git
  - cd tn93/ && cmake ./ && make install && cd ../

install:
  - pip install --upgrade pip
  - pip install biopython
  - pip install numpy
  - travis_wait
  - pip install scipy
  - pip install coveralls

script: 
  - python setup.py install
  - python -c 'import hivtrace'
  - nosetests --with-coverage
notifications:
    email:
        recipients:
            - sweaver@ucsd.edu
        on_success: always
        on_failure: always

after_success:
  - coveralls
